import {
  LayoutDashboard,
  Users,
  Building2,
  FileCheck,
  UsersRound,
  Calendar,
  FileText,
  MessageSquare,
  Megaphone,
  Briefcase,
  Target,
  MapPin,
  Bell,
  Flag,
  Settings,
  Ticket,
  Shield,
  CheckCircle,
} from 'lucide-react';

export const navigationItems = [
  { name: 'Dashboard', icon: LayoutDashboard, path: '/dashboard' },
  { name: 'Admin Management', icon: Shield, path: '/admin-management' },
  { name: 'Pending Approvals', icon: CheckCircle, path: '/pending-approvals' },
  { name: 'Users', icon: Users, path: '/user-management' },
  { name: 'Businesses', icon: Building2, path: '/business-management' },
  { name: 'Promo Codes', icon: Ticket, path: '/promo-codes' },
  { name: 'Communities', icon: UsersRound, path: '/communities' },
  { name: 'Events', icon: Calendar, path: '/events' },
  { name: 'Posts', icon: FileText, path: '/posts' },
  { name: 'Chats', icon: MessageSquare, path: '/chats' },
  { name: 'Ads', icon: Megaphone, path: '/ad-management' },
  { name: 'Jobs', icon: Briefcase, path: '/job-management' },
  { name: 'Matching Engine', icon: Target, path: '/matching-engine' },
  { name: 'Geofencing', icon: MapPin, path: '/geofencing' },
  { name: 'Notifications', icon: Bell, path: '/notifications' },
  { name: 'Reports', icon: Flag, path: '/report-management' },
  { name: 'System Settings', icon: Settings, path: '/system-settings' },
] as const;
